#!/usr/bin/expect

set timeout 5
set command [lindex $argv 0]
spawn telnet localhost 25

expect "220"
send "HELO brdg.me\n"
expect "250"
send "MAIL FROM: vagrant@brdg.me\n"
expect "250"
send "RCPT TO: play@brdg.me\n"
expect "250"
send "DATA\n"
expect "354"
send "$command\n.\nQUIT\n"
