package seven_wonders

const (
	// Age 1
	CardLumberYard      = "Lumber Yard"
	CardStonePit        = "Stone Pit"
	CardClayPool        = "Clay Pool"
	CardOreVein         = "Ore Vein"
	CardTreeFarm        = "Tree Farm"
	CardExcavation      = "Excavation"
	CardClayPit         = "Clay Pit"
	CardTimberYard      = "Timber Yard"
	CardForestCave      = "Forest Cave"
	CardMine            = "Mine"
	CardLoom            = "Loom"
	CardGlassworks      = "Glassworks"
	CardPress           = "Press"
	CardPawnshop        = "Pawnshop"
	CardBaths           = "Baths"
	CardAltar           = "Altar"
	CardTheater         = "Theater"
	CardTavern          = "Tavern"
	CardEastTradingPost = "East Trading Post"
	CardWestTradingPost = "West Trading Post"
	CardMarketplace     = "Marketplace"
	CardStockade        = "Stockade"
	CardBarracks        = "Barracks"
	CardGuardTower      = "Guard Tower"
	CardApothecary      = "Apothecary"
	CardWorkshop        = "Workshop"
	CardScriptorium     = "Scriptorium"

	// Age 2
	CardSawmill        = "Sawmill"
	CardQuarry         = "Quarry"
	CardBrickyard      = "Brickyard"
	CardFoundry        = "Foundry"
	CardAqueduct       = "Aqueduct"
	CardTemple         = "Temple"
	CardStatue         = "Statue"
	CardForum          = "Forum"
	CardCaravansery    = "Caravansery"
	CardVineyard       = "Vineyard"
	CardBazar          = "Bazar"
	CardWalls          = "Walls"
	CardTrainingGround = "Training Ground"
	CardStables        = "Stables"
	CardDispensary     = "Dispensary"
	CardArcheryRange   = "Archery Range"
	CardLaboratory     = "Laboratory"
	CardCourthouse     = "Courthouse"
	CardLibrary        = "Library"
	CardSchool         = "School"

	// Age 3
	CardWorkersGuild      = "Workers Guild"
	CardCraftsmensGuild   = "Craftsmens Guild"
	CardTradersGuild      = "Traders Guild"
	CardPhilosophersGuild = "Philosophers Guild"
	CardSpiesGuild        = "Spies Guild"
	CardStrategistsGuild  = "Strategists Guild"
	CardShipownersGuild   = "Shipowners Guild"
	CardScientistsGuild   = "Scientists Guild"
	CardMagistratesGuild  = "Magistrates Guild"
	CardBuildersGuild     = "Builders Guild"
	CardPantheon          = "Pantheon"
	CardGardens           = "Gardens"
	CardTownHall          = "Town Hall"
	CardPalace            = "Palace"
	CardHaven             = "Haven"
	CardLighthouse        = "Lighthouse"
	CardChamberOfCommerce = "Chamber of Commerce"
	CardFortifications    = "Fortifications"
	CardCircus            = "Circus"
	CardArsenal           = "Arsenal"
	CardArena             = "Arena"
	CardLodge             = "Lodge"
	CardSiegeWorkshop     = "Siege Workshop"
	CardObservatory       = "Observatory"
	CardSenate            = "Senate"
	CardUniversity        = "University"
	CardAcademy           = "Academy"
	CardStudy             = "Study"
)
